### ISSUE TITLE
Reddit data folder is empty

### ISSUE THREAD

**Issue by lslightquantum** [lingjzhu/idiolect#1]
Hi Jian Zhu, thanks for your great work. I'm trying to do some experiments with the Reddit data, but it seems the shared folder for the Reddit data is empty. Could you upload the pre-processed Reddit data? Thank you for your time!

**Comment by lingjzhu** [comment]
Hi! I removed the Reddit data because I think the Reddit license does not allow me to share the data openly. Could you please email me at lingjzhu@umich.edu and then I will share the data to you. Thanks very much for your interest in my work!
